### ISSUE TITLE
An error raised frequently

### ISSUE THREAD

**Issue by biaji** [sualfred/script.embuary.info#63]
With logs:
```
2020-06-22 21:07:22.197 T:3086041984   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--          
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                               
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>                                                             
                                            Error Contents: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)               
                                            Traceback (most recent call last):                                                                             
                                              File "/storage/.kodi/addons/script.embuary.info/plugin.py", line 10, in <module>                             
                                                plugin.run()                                                                                               
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run                          
                                                self._dispatch(self.path)                                                                                  
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch                    
                                                view_func(**kwargs)                                                                                        
                                              File "/storage/.kodi/addons/script.embuary.info/resources/lib/widgets.py", line 349, in movie_listing        
                                                _listing('movie', call, page, pages)                                                                       
                                              File "/storage/.kodi/addons/script.embuary.info/resources/lib/widgets.py", line 383, in _listing             
                                                result, pages = _query(directory, call, params={'page': page})                                             
                                              File "/storage/.kodi/addons/script.embuary.info/resources/lib/widgets.py", line 451, in _query               
                                                params=args                                                                                                
                                              File "/storage/.kodi/addons/script.embuary.info/resources/lib/tmdb.py", line 82, in tmdb_query               
                                                log('%s --> %s' % (error, url), ERROR)                                                                     
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)           
                                            -->End of Python script error report<--    
```                                                             

I'm trying to find what content triggered this error. And will report once I find it.

**Comment by roliverosc** [comment]
i have other bug

```
2020-07-07 10:54:27.686 T:3072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Non-Existent Control 1
                                            Traceback (most recent call last):
                                              File "C:\Users\Usuario\AppData\Roaming\Kodi\addons\script.embuary.info\resources\lib\main.py", line 560, in onInit
                                                self.cont = self.getControl(1)
                                            RuntimeError: Non-Existent Control 1
                                            -->End of Python script error report<--
```

**Comment by biaji** [comment]
if I comment the log line then another error raised:

2020-12-26 18:02:46.030 T:3399852928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                                                                           
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                                                                                                
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>                                                                                                                                              
                                            Error Contents: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)                                                                                                 
                                            Traceback (most recent call last):                                                                                                                                                               
                                              File "/storage/.kodi/addons/script.embuary.info/default.py", line 68, in <module>                                                                                                              
                                                Main()                                                                                                                                                                                      
                                              File "/storage/.kodi/addons/script.embuary.info/default.py", line 32, in __init__                                                                                                             
                                                self.run()                                                                                                                                                                                  
                                              File "/storage/.kodi/addons/script.embuary.info/default.py", line 36, in run                                                                                                                   
                                                TheMovieDB(self.call, self.params)                                                                                                                                                           
                                              File "/storage/.kodi/addons/script.embuary.info/resources/lib/main.py", line 46, in __init__                                                                                                   
                                                self.tmdb_id = self.find_id(method='external_id')                                                                                                                                           
                                              File "/storage/.kodi/addons/script.embuary.info/resources/lib/main.py", line 99, in find_id                                                                                                   
                                                result = tmdb_find(self.call, self.external_id)                                                                                                                                             
                                              File "/storage/.kodi/addons/script.embuary.info/resources/lib/tmdb.py", line 126, in tmdb_find                                                                                                 
                                                show_error=True                                                                                                                                                                              
                                              File "/storage/.kodi/addons/script.embuary.info/resources/lib/tmdb.py", line 84, in tmdb_query                                                                                                 
                                                tmdb_error(error)                                                                                                                                                                           
                                              File "/storage/.kodi/addons/script.embuary.info/resources/lib/tmdb.py", line 239, in tmdb_error                                                                                               
                                                DIALOG.ok(ADDON.getLocalizedString(32000), str(message))                                                                                                                                    
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)                                                                                             
                                            -->End of Python script error report<--
