### ISSUE TITLE
Kodi crashes caused by Embruary Info 'Now playing in theaters' and 'New movies coming soon' widgets

### ISSUE THREAD

**Issue by alphabitnz** [sualfred/script.embuary.info#81]
Have finally managed to isolate this frequent crashing to the Embuary Info skin.
Running Mac OS Monterey, but this issue was also present on Big Sur and possibly earlier.
Kodi Matrix (updating every couple of weeks with Nightlies).

Fault was proven to this script by removing script.embuary.info, which stopped the crashes but started prompting kodi to ask to install this every time kodi starts or stops playback of a video (which were also the points that Kodi would crash).
Then removing the 'Now playing in theaters' and 'New movies coming soon' widgets from my Home widgets stopped Kodi from bugging me with those install prompts.

Best I can do to provide a debug on the crash is below, but let me know if there is a better way I can try to capture the exception:

```
2022-01-15 02:21:30.096 T:380193   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'bytes' object has no attribute 'timestamp'
                                                   Traceback (most recent call last):
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/script.embuary.info/plugin.py", line 5, in <module>
                                                       from resources.lib.widgets import *
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/script.embuary.info/resources/lib/widgets.py", line 11, in <module>
                                                       from resources.lib.helper import *
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/script.embuary.info/resources/lib/helper.py", line 15, in <module>
                                                       import arrow
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/script.module.arrow/lib/arrow/__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/script.module.arrow/lib/arrow/api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/script.module.arrow/lib/arrow/arrow.py", line 34, in <module>
                                                       from arrow import formatter, locales, parser, util
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/script.module.arrow/lib/arrow/parser.py", line 26, in <module>
                                                       from arrow.util import next_weekday, normalize_timestamp
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/script.module.arrow/lib/arrow/util.py", line 6, in <module>
                                                       from arrow.constants import (
                                                     File "/Users/myusername/Library/Application Support/Kodi/addons/script.module.arrow/lib/arrow/constants.py", line 16, in <module>
                                                       _MAX_TIMESTAMP = datetime.max.timestamp()
                                                   AttributeError: 'bytes' object has no attribute 'timestamp'
                                                   -->End of Python script error report<--
```

**Comment by thorindwarf** [comment]
Absolutely the same here.

**Comment by polojoe** [comment]
Same for me.

**Comment by jiminorris** [comment]
I'm also experiencing this, but not on MacOS. Same kind of issue, solved the same way. Not sure if it is the same widgets or a broader issue with tmdb lookup in the script.
Here is the log: https://paste.kodi.tv/elacijupez.kodi
